"use strict";
/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Thu, 01 Dec 2022 16:57:29 GMT
///
/// Parent module: appModule
/// Controller: "appController" registered as "appController" (1 routes)
Object.defineProperty(exports, "__esModule", { value: true });
const central_1 = require("../central");
exports.default = {
    // GET @
    getHello(params, body, query) {
        return (0, central_1.request)('GET', ``, body, query);
    },
};
