"use strict";
/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Thu, 01 Dec 2022 16:32:06 GMT
///
/// Module name: appModule
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.appController = void 0;
var appController_1 = require("./appController");
Object.defineProperty(exports, "appController", { enumerable: true, get: function () { return __importDefault(appController_1).default; } });
