"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.request = void 0;
/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Thu, 01 Dec 2022 16:32:06 GMT
///
var sdk_interface_1 = require("../sdk-interface");
Object.defineProperty(exports, "request", { enumerable: true, get: function () { return sdk_interface_1.request; } });
