/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Thu, 01 Dec 2022 16:57:29 GMT
///
export { request } from '../sdk-interface';
